# Generated by Django 3.2.8 on 2021-10-21 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Battery', 'Battery'), ('Display', 'Display'), ('Touch', 'Touch'), ('Accessories', 'Accessories'), ('Data Cable', 'Data Cable')], default='Battery', max_length=50)),
                ('brand_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='category_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Battery', 'Battery'), ('Display', 'Display'), ('Touch', 'Touch'), ('Accessories', 'Accessories'), ('Data Cable', 'Data Cable')], max_length=50, unique=True)),
                ('category_image', models.ImageField(upload_to='category_image')),
            ],
        ),
        migrations.CreateModel(
            name='product_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.brand')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('product_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Battery', 'Battery'), ('Display', 'Display'), ('Touch', 'Touch'), ('Accessories', 'Accessories'), ('Data Cable', 'Data Cable')], max_length=50)),
                ('product_image', models.ImageField(upload_to='product_image')),
                ('price', models.IntegerField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.brand')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.product_model')),
            ],
        ),
    ]
